"""M0 complete baseline: immutable evidence, case boundaries, and planned store.

Revision ID: 0001_foundation
The SQL is intentionally frozen here, independent of application metadata.
"""

from alembic import op

revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        "CREATE TABLE users (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tusername TEXT NOT NULL, \n\tdisplay_name TEXT NOT NULL, \n\tpassword_hash TEXT NOT NULL, \n\tglobal_role TEXT NOT NULL, \n\tis_active BOOLEAN NOT NULL, \n\tmust_change_password BOOLEAN NOT NULL, \n\tfailed_logins INTEGER NOT NULL, \n\tlocked_until TIMESTAMP WITH TIME ZONE, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_users PRIMARY KEY (id), \n\tCONSTRAINT ck_users_global_role CHECK (global_role IN ('ADMIN', 'INVESTIGATOR', 'VIEWER')), \n\tCONSTRAINT uq_users_username UNIQUE (username)\n)"
    )
    op.execute(
        "CREATE TABLE taxonomy_terms (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcanonical TEXT NOT NULL, \n\ttype TEXT NOT NULL, \n\tterm TEXT NOT NULL, \n\tlanguage TEXT NOT NULL, \n\tscript TEXT NOT NULL, \n\tnote TEXT, \n\tactive BOOLEAN NOT NULL, \n\tversion INTEGER NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_taxonomy_terms PRIMARY KEY (id), \n\tCONSTRAINT uq_taxonomy_terms_canonical_term_language_script UNIQUE (canonical, term, language, script), \n\tCONSTRAINT ck_taxonomy_terms_type CHECK (type IN ('SUBSTANCE', 'SLANG', 'VENDOR_ALIAS', 'MARKETPLACE', 'LOCATION', 'SHIPPING_TERM', 'PACKAGING_TERM', 'PRICE', 'QUANTITY', 'CURRENCY', 'CONTACT_HANDLE', 'EMAIL', 'PHONE', 'PGP_KEY', 'PGP_FINGERPRINT', 'BTC_ADDRESS', 'ETH_ADDRESS', 'XMR_ADDRESS', 'TRON_ADDRESS', 'URL', 'ONION_LOCATOR', 'IMAGE_REFERENCE', 'SLANG_CANDIDATE'))\n)"
    )
    op.execute(
        "CREATE TABLE tool_registry (\n\tname TEXT NOT NULL, \n\tkind TEXT NOT NULL, \n\tserver TEXT, \n\tlane TEXT NOT NULL, \n\trequires_network BOOLEAN NOT NULL, \n\tsource_class TEXT, \n\tpolicy_tags TEXT[] NOT NULL, \n\trate_key TEXT, \n\trate_cap_per_hour INTEGER, \n\tenabled BOOLEAN NOT NULL, \n\thealth JSONB NOT NULL, \n\tlast_health_at TIMESTAMP WITH TIME ZONE, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_tool_registry PRIMARY KEY (name), \n\tCONSTRAINT ck_tool_registry_source_class CHECK (source_class IN ('SYNTHETIC', 'SEIZED', 'UPLOAD', 'OSINT_SURFACE', 'OSINT_DARK', 'CHAIN', 'TELEGRAM', 'REPORT'))\n)"
    )
    op.execute(
        "CREATE TABLE sessions (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tuser_id UUID NOT NULL, \n\trefresh_hash TEXT NOT NULL, \n\tcsrf_hash TEXT NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\trotated_from UUID, \n\tip INET, \n\tuser_agent TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_sessions PRIMARY KEY (id), \n\tCONSTRAINT fk_sessions_user_id_users FOREIGN KEY(user_id) REFERENCES users (id), \n\tCONSTRAINT uq_sessions_refresh_hash UNIQUE (refresh_hash), \n\tCONSTRAINT fk_sessions_rotated_from_sessions FOREIGN KEY(rotated_from) REFERENCES sessions (id)\n)"
    )
    op.execute(
        "CREATE TABLE cases (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcode TEXT NOT NULL, \n\ttitle TEXT NOT NULL, \n\tstatus TEXT DEFAULT 'OPEN' NOT NULL, \n\tscope_notes TEXT, \n\tauthority_ref_enc BYTEA, \n\tauthority_ref_bidx TEXT, \n\tsource_policy JSONB NOT NULL, \n\tlegal_hold BOOLEAN NOT NULL, \n\tdemo BOOLEAN NOT NULL, \n\tcreated_by UUID NOT NULL, \n\topened_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tclosed_at TIMESTAMP WITH TIME ZONE, \n\tarchived_at TIMESTAMP WITH TIME ZONE, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_cases PRIMARY KEY (id), \n\tCONSTRAINT ck_cases_status CHECK (status IN ('OPEN', 'CLOSED', 'ARCHIVED')), \n\tCONSTRAINT uq_cases_code UNIQUE (code), \n\tCONSTRAINT fk_cases_created_by_users FOREIGN KEY(created_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE settings (\n\tkey TEXT NOT NULL, \n\tvalue JSONB NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tupdated_by UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_settings PRIMARY KEY (key), \n\tCONSTRAINT fk_settings_updated_by_users FOREIGN KEY(updated_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE threads (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\ttitle TEXT NOT NULL, \n\tgoal TEXT, \n\tstatus TEXT DEFAULT 'OPEN' NOT NULL, \n\tharness TEXT DEFAULT 'DETERMINISTIC' NOT NULL, \n\tharness_session_id UUID, \n\tsummary TEXT, \n\tsummary_updated_at TIMESTAMP WITH TIME ZONE, \n\tpinned_finding_ids UUID[] NOT NULL, \n\tbudget_usd NUMERIC(12, 4) NOT NULL, \n\tspent_usd NUMERIC(12, 4) NOT NULL, \n\tassignee_id UUID, \n\tcreated_by UUID NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tlast_message_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_threads PRIMARY KEY (id), \n\tCONSTRAINT uq_threads_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT ck_threads_status CHECK (status IN ('OPEN', 'CLOSED')), \n\tCONSTRAINT ck_threads_harness CHECK (harness IN ('CLAUDE', 'OFFLINE', 'FAKE', 'DETERMINISTIC')), \n\tCONSTRAINT fk_threads_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_threads_assignee_id_users FOREIGN KEY(assignee_id) REFERENCES users (id), \n\tCONSTRAINT fk_threads_created_by_users FOREIGN KEY(created_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE rate_counters (\n\tcase_id UUID NOT NULL, \n\trate_key TEXT NOT NULL, \n\twindow_start TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcount INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_rate_counters PRIMARY KEY (case_id, rate_key, window_start), \n\tCONSTRAINT fk_rate_counters_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE analytic_runs (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tkind TEXT NOT NULL, \n\tversion TEXT NOT NULL, \n\tconfig_digest TEXT NOT NULL, \n\tstatus TEXT NOT NULL, \n\tstats JSONB NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\terror TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_analytic_runs PRIMARY KEY (id), \n\tCONSTRAINT uq_analytic_runs_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_analytic_runs_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE trend_buckets (\n\tcase_id UUID NOT NULL, \n\tsubject_type TEXT NOT NULL, \n\tsubject TEXT NOT NULL, \n\tday DATE NOT NULL, \n\tcount INTEGER NOT NULL, \n\tunique_evidence_families INTEGER NOT NULL, \n\tunique_aliases INTEGER NOT NULL, \n\tunique_sources INTEGER NOT NULL, \n\tcomputed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_trend_buckets PRIMARY KEY (case_id, subject_type, subject, day), \n\tCONSTRAINT fk_trend_buckets_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE ledger_nodes (\n\tcase_id UUID NOT NULL, \n\tnode_index INTEGER NOT NULL, \n\ttxid TEXT NOT NULL, \n\ttimestep INTEGER NOT NULL, \n\tlabel INTEGER NOT NULL, \n\tfeatures FLOAT[] NOT NULL, \n\timported_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_ledger_nodes PRIMARY KEY (case_id, node_index), \n\tCONSTRAINT ck_ledger_nodes_feature_count CHECK (cardinality(features) = 102), \n\tCONSTRAINT fk_ledger_nodes_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE api_tokens (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tname TEXT NOT NULL, \n\towner_user_id UUID NOT NULL, \n\ttoken_hash TEXT NOT NULL, \n\tscopes TEXT[] NOT NULL, \n\tcase_id UUID, \n\texpires_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\trevoked_at TIMESTAMP WITH TIME ZONE, \n\tlast_used_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_api_tokens PRIMARY KEY (id), \n\tCONSTRAINT fk_api_tokens_owner_user_id_users FOREIGN KEY(owner_user_id) REFERENCES users (id), \n\tCONSTRAINT uq_api_tokens_token_hash UNIQUE (token_hash), \n\tCONSTRAINT fk_api_tokens_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE case_memberships (\n\tcase_id UUID NOT NULL, \n\tuser_id UUID NOT NULL, \n\trole TEXT NOT NULL, \n\tadded_by UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_case_memberships PRIMARY KEY (case_id, user_id), \n\tCONSTRAINT ck_case_memberships_role CHECK (role IN ('OWNER', 'LEAD', 'ANALYST', 'VIEWER')), \n\tCONSTRAINT fk_case_memberships_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_case_memberships_user_id_users FOREIGN KEY(user_id) REFERENCES users (id), \n\tCONSTRAINT fk_case_memberships_added_by_users FOREIGN KEY(added_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE decisions (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\ttarget_type TEXT NOT NULL, \n\ttarget_id UUID NOT NULL, \n\ttarget_version INTEGER NOT NULL, \n\tdecision TEXT NOT NULL, \n\trationale TEXT NOT NULL, \n\tdecided_by UUID NOT NULL, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tsupersedes_id UUID, \n\trequest_id TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_decisions PRIMARY KEY (id), \n\tCONSTRAINT uq_decisions_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_decisions_case_id_target_type_target_id_target_version_id UNIQUE (case_id, target_type, target_id, target_version, id), \n\tCONSTRAINT ck_decisions_no_self_supersession CHECK (supersedes_id IS NULL OR supersedes_id <> id), \n\tCONSTRAINT ck_decisions_target_type CHECK (target_type IN ('LINK', 'ACTIVITY', 'ALERT', 'FINDING')), \n\tCONSTRAINT ck_decisions_decision CHECK (decision IN ('ACCEPT', 'REJECT', 'DEFER', 'REQUEST_MORE_EVIDENCE')), \n\tCONSTRAINT fk_decisions_supersedes_id_decisions FOREIGN KEY(case_id, target_type, target_id, target_version, supersedes_id) REFERENCES decisions (case_id, target_type, target_id, target_version, id), \n\tCONSTRAINT fk_decisions_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_decisions_decided_by_users FOREIGN KEY(decided_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE evidence (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tcode TEXT NOT NULL, \n\tsha256 TEXT NOT NULL, \n\tsize_bytes BIGINT NOT NULL, \n\tmime TEXT NOT NULL, \n\tkind TEXT NOT NULL, \n\toriginal_filename TEXT NOT NULL, \n\tstorage_key TEXT NOT NULL, \n\tsource_class TEXT NOT NULL, \n\torigin TEXT NOT NULL, \n\tstatus TEXT DEFAULT 'PROCESSING' NOT NULL, \n\tlocator_enc BYTEA, \n\tlocator_bidx TEXT, \n\tcaptured_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\trequested_by_kind TEXT NOT NULL, \n\trequested_by_id UUID, \n\tparent_evidence_id UUID, \n\ttransformation TEXT, \n\twarnings JSONB NOT NULL, \n\tmeta JSONB NOT NULL, \n\tcreated_by_kind TEXT NOT NULL, \n\tcreated_by_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_evidence PRIMARY KEY (id), \n\tCONSTRAINT uq_evidence_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_evidence_case_id_code UNIQUE (case_id, code), \n\tCONSTRAINT uq_evidence_case_id_sha256 UNIQUE (case_id, sha256), \n\tCONSTRAINT ck_evidence_kind CHECK (kind IN ('PDF', 'HTML', 'WARC', 'IMAGE', 'CSV', 'JSON', 'TEXT', 'ZIP', 'AUDIO', 'VIDEO', 'OFFICE', 'UNKNOWN')), \n\tCONSTRAINT ck_evidence_source_class CHECK (source_class IN ('SYNTHETIC', 'SEIZED', 'UPLOAD', 'OSINT_SURFACE', 'OSINT_DARK', 'CHAIN', 'TELEGRAM', 'REPORT')), \n\tCONSTRAINT ck_evidence_origin CHECK (origin IN ('UPLOAD', 'CAPTURE', 'MONITOR', 'DERIVATIVE', 'REPORT')), \n\tCONSTRAINT ck_evidence_status CHECK (status IN ('PROCESSING', 'READY', 'PARTIAL', 'QUARANTINED', 'FAILED', 'EXPIRED')), \n\tCONSTRAINT ck_evidence_requested_by_kind CHECK (requested_by_kind IN ('USER', 'THREAD', 'WATCHLIST_ITEM', 'SYSTEM')), \n\tCONSTRAINT fk_evidence_parent_evidence_id_evidence FOREIGN KEY(case_id, parent_evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT ck_evidence_created_by_kind CHECK (created_by_kind IN ('USER', 'TOKEN', 'SYSTEM', 'MODEL')), \n\tCONSTRAINT fk_evidence_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE evidence_code_counters (\n\tcase_id UUID NOT NULL, \n\tnext INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_evidence_code_counters PRIMARY KEY (case_id), \n\tCONSTRAINT fk_evidence_code_counters_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE canonical_entities (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\ttype TEXT NOT NULL, \n\tvalue TEXT NOT NULL, \n\tdisplay TEXT NOT NULL, \n\tfirst_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tobservation_count INTEGER NOT NULL, \n\tattrs JSONB NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_canonical_entities PRIMARY KEY (id), \n\tCONSTRAINT uq_canonical_entities_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_canonical_entities_case_id_type_value UNIQUE (case_id, type, value), \n\tCONSTRAINT ck_canonical_entities_type CHECK (type IN ('SUBSTANCE', 'SLANG', 'VENDOR_ALIAS', 'MARKETPLACE', 'LOCATION', 'SHIPPING_TERM', 'PACKAGING_TERM', 'PRICE', 'QUANTITY', 'CURRENCY', 'CONTACT_HANDLE', 'EMAIL', 'PHONE', 'PGP_KEY', 'PGP_FINGERPRINT', 'BTC_ADDRESS', 'ETH_ADDRESS', 'XMR_ADDRESS', 'TRON_ADDRESS', 'URL', 'ONION_LOCATOR', 'IMAGE_REFERENCE', 'SLANG_CANDIDATE')), \n\tCONSTRAINT fk_canonical_entities_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE watchlists (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tname TEXT NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tcreated_by UUID NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_watchlists PRIMARY KEY (id), \n\tCONSTRAINT uq_watchlists_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_watchlists_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_watchlists_created_by_users FOREIGN KEY(created_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE policy_decisions (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\ttool TEXT NOT NULL, \n\tallow BOOLEAN NOT NULL, \n\trule TEXT NOT NULL, \n\treason TEXT NOT NULL, \n\targs_hash TEXT NOT NULL, \n\trequester_kind TEXT NOT NULL, \n\trequester_id UUID, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_policy_decisions PRIMARY KEY (id), \n\tCONSTRAINT uq_policy_decisions_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT ck_policy_decisions_requester_kind CHECK (requester_kind IN ('USER', 'THREAD', 'WATCHLIST_ITEM', 'SYSTEM')), \n\tCONSTRAINT fk_policy_decisions_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE runs (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tthread_id UUID NOT NULL, \n\tstatus TEXT DEFAULT 'QUEUED' NOT NULL, \n\tharness TEXT NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tcost_usd NUMERIC(12, 4) NOT NULL, \n\ttokens_in INTEGER NOT NULL, \n\ttokens_out INTEGER NOT NULL, \n\terror JSONB, \n\tcancel_requested BOOLEAN NOT NULL, \n\treplayed_from_run_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_runs PRIMARY KEY (id), \n\tCONSTRAINT uq_runs_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_agent_thread_id_threads FOREIGN KEY(case_id, thread_id) REFERENCES threads (case_id, id), \n\tCONSTRAINT ck_runs_status CHECK (status IN ('QUEUED', 'RUNNING', 'DONE', 'ERROR', 'CANCELLED', 'BUDGET')), \n\tCONSTRAINT ck_runs_harness CHECK (harness IN ('CLAUDE', 'OFFLINE', 'FAKE', 'DETERMINISTIC')), \n\tCONSTRAINT fk_agent_replayed_from_run_id_runs FOREIGN KEY(case_id, replayed_from_run_id) REFERENCES runs (case_id, id), \n\tCONSTRAINT fk_runs_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE link_candidates (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\tsubject_a_id UUID NOT NULL, \n\tsubject_b_id UUID NOT NULL, \n\tscore INTEGER NOT NULL, \n\tband TEXT NOT NULL, \n\tfeatures JSONB NOT NULL, \n\tevidence_ids UUID[] NOT NULL, \n\tcontradictions JSONB NOT NULL, \n\tfamilies TEXT[] NOT NULL, \n\tstatus TEXT DEFAULT 'PENDING' NOT NULL, \n\tversion INTEGER NOT NULL, \n\tsupersedes_id UUID, \n\tfeature_digest TEXT NOT NULL, \n\tmeta JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_link_candidates PRIMARY KEY (id), \n\tCONSTRAINT uq_link_candidates_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_link_candidates_case_id_subject_a_id_subject_b_id_version UNIQUE (case_id, subject_a_id, subject_b_id, version), \n\tCONSTRAINT fk_analytics_run_id_analytic_runs FOREIGN KEY(case_id, run_id) REFERENCES analytic_runs (case_id, id), \n\tCONSTRAINT fk_analytics_subject_a_id_canonical_entities FOREIGN KEY(case_id, subject_a_id) REFERENCES canonical_entities (case_id, id), \n\tCONSTRAINT fk_analytics_subject_b_id_canonical_entities FOREIGN KEY(case_id, subject_b_id) REFERENCES canonical_entities (case_id, id), \n\tCONSTRAINT ck_link_candidates_band CHECK (band IN ('WEAK', 'POSSIBLE', 'LEAD', 'STRONG')), \n\tCONSTRAINT ck_link_candidates_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DEFERRED')), \n\tCONSTRAINT fk_analytics_supersedes_id_link_candidates FOREIGN KEY(case_id, supersedes_id) REFERENCES link_candidates (case_id, id), \n\tCONSTRAINT ck_link_candidates_ordered_subjects CHECK (subject_a_id < subject_b_id), \n\tCONSTRAINT fk_link_candidates_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE activity_candidates (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\tevidence_id UUID NOT NULL, \n\tscore FLOAT NOT NULL, \n\tlabel TEXT NOT NULL, \n\tfeatures JSONB NOT NULL, \n\tstatus TEXT DEFAULT 'PENDING' NOT NULL, \n\tversion INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_activity_candidates PRIMARY KEY (id), \n\tCONSTRAINT uq_activity_candidates_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_activity_candidates_case_id_evidence_id_version UNIQUE (case_id, evidence_id, version), \n\tCONSTRAINT fk_analytics_run_id_analytic_runs FOREIGN KEY(case_id, run_id) REFERENCES analytic_runs (case_id, id), \n\tCONSTRAINT fk_analytics_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT ck_activity_candidates_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'DEFERRED')), \n\tCONSTRAINT fk_activity_candidates_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE wallet_assessments (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\taddress TEXT NOT NULL, \n\tchain TEXT NOT NULL, \n\tgnn JSONB, \n\tgnn_unavailable_reason TEXT, \n\tsanctions JSONB, \n\tlive_summary JSONB, \n\tlive_summary_evidence_id UUID, \n\ttags TEXT[] NOT NULL, \n\ttraceable BOOLEAN NOT NULL, \n\tassessed_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tversion INTEGER NOT NULL, \n\trequested_by_kind TEXT NOT NULL, \n\trequested_by_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_wallet_assessments PRIMARY KEY (id), \n\tCONSTRAINT uq_wallet_assessments_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_analytics_live_summary_evidence_id_evidence FOREIGN KEY(case_id, live_summary_evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT ck_wallet_assessments_requested_by_kind CHECK (requested_by_kind IN ('USER', 'THREAD', 'WATCHLIST_ITEM', 'SYSTEM')), \n\tCONSTRAINT fk_wallet_assessments_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE ledger_edges (\n\tcase_id UUID NOT NULL, \n\tsrc INTEGER NOT NULL, \n\tdst INTEGER NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_ledger_edges PRIMARY KEY (case_id, src, dst), \n\tCONSTRAINT fk_analytics_src_ledger_nodes FOREIGN KEY(case_id, src) REFERENCES ledger_nodes (case_id, node_index), \n\tCONSTRAINT fk_analytics_dst_ledger_nodes FOREIGN KEY(case_id, dst) REFERENCES ledger_nodes (case_id, node_index), \n\tCONSTRAINT fk_ledger_edges_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE ledger_addresses (\n\tcase_id UUID NOT NULL, \n\taddress TEXT NOT NULL, \n\tchain TEXT NOT NULL, \n\tnode_index INTEGER NOT NULL, \n\ttag TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_ledger_addresses PRIMARY KEY (case_id, address), \n\tCONSTRAINT fk_analytics_node_index_ledger_nodes FOREIGN KEY(case_id, node_index) REFERENCES ledger_nodes (case_id, node_index), \n\tCONSTRAINT fk_ledger_addresses_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE custody_events (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tevidence_id UUID NOT NULL, \n\taction TEXT NOT NULL, \n\tactor_kind TEXT NOT NULL, \n\tactor_id UUID, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\thash_verified BOOLEAN, \n\tnote TEXT, \n\trequest_id TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_custody_events PRIMARY KEY (id), \n\tCONSTRAINT uq_custody_events_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_evidence_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT ck_custody_events_action CHECK (action IN ('INGESTED', 'VERIFIED', 'DERIVED', 'VIEWED_ORIGINAL', 'EXPORTED', 'QUARANTINED', 'RELEASED')), \n\tCONSTRAINT ck_custody_events_actor_kind CHECK (actor_kind IN ('USER', 'TOKEN', 'SYSTEM', 'MODEL')), \n\tCONSTRAINT fk_custody_events_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE derivatives (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tevidence_id UUID NOT NULL, \n\tkind TEXT NOT NULL, \n\tversion INTEGER NOT NULL, \n\tstorage_key TEXT NOT NULL, \n\tstatus TEXT NOT NULL, \n\textractor TEXT NOT NULL, \n\textractor_version TEXT NOT NULL, \n\tlang_tags TEXT[] NOT NULL, \n\tscript_tags TEXT[] NOT NULL, \n\ttext_len INTEGER, \n\tmeta JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_derivatives PRIMARY KEY (id), \n\tCONSTRAINT uq_derivatives_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_derivatives_evidence_id_kind_version UNIQUE (evidence_id, kind, version), \n\tCONSTRAINT fk_evidence_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT ck_derivatives_kind CHECK (kind IN ('TEXT', 'OCR', 'TRANSCRIPT', 'IMAGE_META', 'ROWS', 'MESSAGES', 'HTML_SAFE')), \n\tCONSTRAINT fk_derivatives_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE extraction_runs (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tevidence_id UUID, \n\tbundle_version TEXT NOT NULL, \n\tstatus TEXT NOT NULL, \n\tstats JSONB NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\terror TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_extraction_runs PRIMARY KEY (id), \n\tCONSTRAINT uq_extraction_runs_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_extract_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT fk_extraction_runs_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE watchlist_items (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\twatchlist_id UUID NOT NULL, \n\ttype TEXT NOT NULL, \n\tvalue TEXT NOT NULL, \n\tvalue_norm TEXT NOT NULL, \n\tvariants TEXT[] NOT NULL, \n\tsources TEXT[] NOT NULL, \n\tinterval_seconds INTEGER NOT NULL, \n\tactive BOOLEAN NOT NULL, \n\tnote TEXT, \n\tstate JSONB NOT NULL, \n\tlast_run_at TIMESTAMP WITH TIME ZONE, \n\tnext_run_at TIMESTAMP WITH TIME ZONE, \n\tcreated_by UUID NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_watchlist_items PRIMARY KEY (id), \n\tCONSTRAINT uq_watchlist_items_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_watchlist_items_case_id_type_value_norm UNIQUE (case_id, type, value_norm), \n\tCONSTRAINT fk_monitor_watchlist_id_watchlists FOREIGN KEY(case_id, watchlist_id) REFERENCES watchlists (case_id, id), \n\tCONSTRAINT ck_watchlist_items_type CHECK (type IN ('KEYWORD', 'ALIAS', 'WALLET', 'PGP_FINGERPRINT', 'ONION_DOMAIN', 'TELEGRAM_CHANNEL', 'IMAGE_HASH')), \n\tCONSTRAINT fk_watchlist_items_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_watchlist_items_created_by_users FOREIGN KEY(created_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE reports (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tversion INTEGER NOT NULL, \n\tevidence_id UUID, \n\tstorage_key_md TEXT, \n\tstorage_key_html TEXT, \n\tsha256 TEXT, \n\tgenerated_by UUID NOT NULL, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tincludes JSONB NOT NULL, \n\tclaim_check JSONB NOT NULL, \n\tredaction JSONB NOT NULL, \n\tstatus TEXT NOT NULL, \n\terror TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_reports PRIMARY KEY (id), \n\tCONSTRAINT uq_reports_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_reports_case_id_version UNIQUE (case_id, version), \n\tCONSTRAINT fk_reports_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT fk_reports_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_reports_generated_by_users FOREIGN KEY(generated_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE messages (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tthread_id UUID NOT NULL, \n\trun_id UUID, \n\trole TEXT NOT NULL, \n\tblocks JSONB NOT NULL, \n\ttext TEXT NOT NULL, \n\tclaims JSONB NOT NULL, \n\tverification JSONB, \n\ttokens_in INTEGER NOT NULL, \n\ttokens_out INTEGER NOT NULL, \n\tcost_usd NUMERIC(12, 4) NOT NULL, \n\tharness TEXT, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_messages PRIMARY KEY (id), \n\tCONSTRAINT uq_messages_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_agent_thread_id_threads FOREIGN KEY(case_id, thread_id) REFERENCES threads (case_id, id), \n\tCONSTRAINT fk_agent_run_id_runs FOREIGN KEY(case_id, run_id) REFERENCES runs (case_id, id), \n\tCONSTRAINT ck_messages_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM', 'TOOL')), \n\tCONSTRAINT ck_messages_harness CHECK (harness IN ('CLAUDE', 'OFFLINE', 'FAKE', 'DETERMINISTIC')), \n\tCONSTRAINT fk_messages_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE tool_calls (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\tthread_id UUID NOT NULL, \n\tseq INTEGER NOT NULL, \n\ttool TEXT NOT NULL, \n\targs JSONB NOT NULL, \n\targs_hash TEXT NOT NULL, \n\tpolicy_decision JSONB, \n\tstatus TEXT NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tduration_ms INTEGER, \n\tresult_hash TEXT, \n\tresult_evidence_ids UUID[] NOT NULL, \n\terror JSONB, \n\tcached BOOLEAN NOT NULL, \n\trequester_kind TEXT NOT NULL, \n\trequester_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_tool_calls PRIMARY KEY (id), \n\tCONSTRAINT uq_tool_calls_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_agent_run_id_runs FOREIGN KEY(case_id, run_id) REFERENCES runs (case_id, id), \n\tCONSTRAINT fk_agent_thread_id_threads FOREIGN KEY(case_id, thread_id) REFERENCES threads (case_id, id), \n\tCONSTRAINT ck_tool_calls_requester_kind CHECK (requester_kind IN ('USER', 'THREAD', 'WATCHLIST_ITEM', 'SYSTEM')), \n\tCONSTRAINT fk_tool_calls_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE run_events (\n\tcase_id UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\tseq INTEGER NOT NULL, \n\ttype TEXT NOT NULL, \n\tdata JSONB NOT NULL, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_run_events PRIMARY KEY (run_id, seq), \n\tCONSTRAINT fk_agent_run_id_runs FOREIGN KEY(case_id, run_id) REFERENCES runs (case_id, id), \n\tCONSTRAINT fk_run_events_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE replay_entries (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tquestion_norm TEXT NOT NULL, \n\tharness TEXT NOT NULL, \n\trun_id UUID NOT NULL, \n\tevent_log JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_replay_entries PRIMARY KEY (id), \n\tCONSTRAINT uq_replay_entries_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_replay_entries_case_id_question_norm_harness UNIQUE (case_id, question_norm, harness), \n\tCONSTRAINT ck_replay_entries_harness CHECK (harness IN ('CLAUDE', 'OFFLINE', 'FAKE', 'DETERMINISTIC')), \n\tCONSTRAINT fk_agent_run_id_runs FOREIGN KEY(case_id, run_id) REFERENCES runs (case_id, id), \n\tCONSTRAINT fk_replay_entries_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE graph_edges (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tsrc_entity_id UUID NOT NULL, \n\tdst_entity_id UUID NOT NULL, \n\ttype TEXT NOT NULL, \n\tstatus TEXT NOT NULL, \n\tscore FLOAT, \n\tfamilies TEXT[] NOT NULL, \n\tcandidate_id UUID, \n\tdecision_id UUID, \n\tprovenance JSONB NOT NULL, \n\tfirst_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tupdated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_graph_edges PRIMARY KEY (id), \n\tCONSTRAINT uq_graph_edges_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_graph_edges_case_id_src_entity_id_dst_entity_id_type UNIQUE (case_id, src_entity_id, dst_entity_id, type), \n\tCONSTRAINT fk_analytics_src_entity_id_canonical_entities FOREIGN KEY(case_id, src_entity_id) REFERENCES canonical_entities (case_id, id), \n\tCONSTRAINT fk_analytics_dst_entity_id_canonical_entities FOREIGN KEY(case_id, dst_entity_id) REFERENCES canonical_entities (case_id, id), \n\tCONSTRAINT ck_graph_edges_type CHECK (type IN ('CO_OCCURS', 'USES', 'POSSIBLE_SAME_OPERATOR', 'ANALYST_CONFIRMED_RELATED', 'MENTIONS_LOCATION', 'CONTAINS')), \n\tCONSTRAINT ck_graph_edges_status CHECK (status IN ('PENDING', 'CONFIRMED', 'REJECTED', 'INFO')), \n\tCONSTRAINT fk_analytics_candidate_id_link_candidates FOREIGN KEY(case_id, candidate_id) REFERENCES link_candidates (case_id, id), \n\tCONSTRAINT fk_analytics_decision_id_decisions FOREIGN KEY(case_id, decision_id) REFERENCES decisions (case_id, id), \n\tCONSTRAINT fk_graph_edges_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE audit_events (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tactor_kind TEXT NOT NULL, \n\tactor_id UUID, \n\tcase_id UUID, \n\tthread_id UUID, \n\trun_id UUID, \n\taction TEXT NOT NULL, \n\ttarget_type TEXT, \n\ttarget_id UUID, \n\tdetail JSONB NOT NULL, \n\tresult_hash TEXT, \n\trequest_id TEXT, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_audit_events PRIMARY KEY (id), \n\tCONSTRAINT ck_audit_events_actor_kind CHECK (actor_kind IN ('USER', 'TOKEN', 'SYSTEM', 'MODEL')), \n\tCONSTRAINT fk_audit_events_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_audit_events_thread_id_threads FOREIGN KEY(thread_id) REFERENCES threads (id), \n\tCONSTRAINT fk_audit_events_run_id_runs FOREIGN KEY(run_id) REFERENCES runs (id)\n)"
    )
    op.execute(
        "CREATE TABLE observations (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tevidence_id UUID NOT NULL, \n\tderivative_id UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\ttype TEXT NOT NULL, \n\traw TEXT NOT NULL, \n\tnormalized JSONB NOT NULL, \n\tcanonical_entity_id UUID, \n\tspan_start INTEGER NOT NULL, \n\tspan_end INTEGER NOT NULL, \n\tline_no INTEGER, \n\tvalidator TEXT NOT NULL, \n\tvalid BOOLEAN NOT NULL, \n\tconfidence FLOAT NOT NULL, \n\tmeta JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_observations PRIMARY KEY (id), \n\tCONSTRAINT uq_observations_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_extract_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT fk_extract_derivative_id_derivatives FOREIGN KEY(case_id, derivative_id) REFERENCES derivatives (case_id, id), \n\tCONSTRAINT fk_extract_run_id_extraction_runs FOREIGN KEY(case_id, run_id) REFERENCES extraction_runs (case_id, id), \n\tCONSTRAINT ck_observations_type CHECK (type IN ('SUBSTANCE', 'SLANG', 'VENDOR_ALIAS', 'MARKETPLACE', 'LOCATION', 'SHIPPING_TERM', 'PACKAGING_TERM', 'PRICE', 'QUANTITY', 'CURRENCY', 'CONTACT_HANDLE', 'EMAIL', 'PHONE', 'PGP_KEY', 'PGP_FINGERPRINT', 'BTC_ADDRESS', 'ETH_ADDRESS', 'XMR_ADDRESS', 'TRON_ADDRESS', 'URL', 'ONION_LOCATOR', 'IMAGE_REFERENCE', 'SLANG_CANDIDATE')), \n\tCONSTRAINT fk_extract_canonical_entity_id_canonical_entities FOREIGN KEY(case_id, canonical_entity_id) REFERENCES canonical_entities (case_id, id), \n\tCONSTRAINT ck_observations_span CHECK (span_end > span_start AND span_start >= 0), \n\tCONSTRAINT ck_observations_confidence_range CHECK (confidence >= 0 AND confidence <= 1), \n\tCONSTRAINT fk_observations_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE monitor_runs (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\titem_id UUID NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tfinished_at TIMESTAMP WITH TIME ZONE, \n\tstatus TEXT NOT NULL, \n\tmanual BOOLEAN NOT NULL, \n\tsources_run JSONB NOT NULL, \n\tnew_hits INTEGER NOT NULL, \n\terrors JSONB NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_monitor_runs PRIMARY KEY (id), \n\tCONSTRAINT uq_monitor_runs_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_monitor_item_id_watchlist_items FOREIGN KEY(case_id, item_id) REFERENCES watchlist_items (case_id, id), \n\tCONSTRAINT fk_monitor_runs_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE monitor_seen_urls (\n\tcase_id UUID NOT NULL, \n\titem_id UUID NOT NULL, \n\turl_hash TEXT NOT NULL, \n\tfirst_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tlast_seen_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_monitor_seen_urls PRIMARY KEY (item_id, url_hash), \n\tCONSTRAINT fk_monitor_item_id_watchlist_items FOREIGN KEY(case_id, item_id) REFERENCES watchlist_items (case_id, id), \n\tCONSTRAINT fk_monitor_seen_urls_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE chunks (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tevidence_id UUID NOT NULL, \n\tderivative_id UUID NOT NULL, \n\tderivative_version INTEGER NOT NULL, \n\tordinal INTEGER NOT NULL, \n\tkind TEXT NOT NULL, \n\ttext TEXT NOT NULL, \n\tsearch_text TEXT NOT NULL, \n\tspan_start INTEGER NOT NULL, \n\tspan_end INTEGER NOT NULL, \n\tline_no INTEGER, \n\tlang TEXT NOT NULL, \n\tscript TEXT NOT NULL, \n\tsource_class TEXT NOT NULL, \n\ttsv TSVECTOR GENERATED ALWAYS AS (to_tsvector('simple', search_text)) STORED NOT NULL, \n\tembedding VECTOR(1024), \n\tembedding_model TEXT, \n\tembedded_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_chunks PRIMARY KEY (id), \n\tCONSTRAINT uq_chunks_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_chunks_derivative_id_derivative_version_ordinal UNIQUE (derivative_id, derivative_version, ordinal), \n\tCONSTRAINT fk_rag_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT fk_rag_derivative_id_derivatives FOREIGN KEY(case_id, derivative_id) REFERENCES derivatives (case_id, id), \n\tCONSTRAINT ck_chunks_source_class CHECK (source_class IN ('SYNTHETIC', 'SEIZED', 'UPLOAD', 'OSINT_SURFACE', 'OSINT_DARK', 'CHAIN', 'TELEGRAM', 'REPORT')), \n\tCONSTRAINT ck_chunks_span CHECK (span_end > span_start AND span_start >= 0), \n\tCONSTRAINT fk_chunks_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute(
        "CREATE TABLE findings (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tthread_id UUID, \n\ttitle TEXT NOT NULL, \n\tclaim TEXT NOT NULL, \n\tkind TEXT NOT NULL, \n\tevidence_ids UUID[] NOT NULL, \n\tmethod TEXT NOT NULL, \n\tmethod_version TEXT, \n\tconfidence FLOAT, \n\tstatus TEXT DEFAULT 'DRAFT' NOT NULL, \n\tversion INTEGER NOT NULL, \n\tsupersedes_id UUID, \n\tsource_message_id UUID, \n\tclaim_index INTEGER, \n\tdecision_id UUID, \n\tcreated_by UUID NOT NULL, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_findings PRIMARY KEY (id), \n\tCONSTRAINT uq_findings_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT fk_decisions_thread_id_threads FOREIGN KEY(case_id, thread_id) REFERENCES threads (case_id, id), \n\tCONSTRAINT ck_findings_kind CHECK (kind IN ('OBSERVED', 'MODEL', 'CANDIDATE', 'CONFIRMED')), \n\tCONSTRAINT ck_findings_status CHECK (status IN ('DRAFT', 'PROMOTED', 'SUPERSEDED')), \n\tCONSTRAINT fk_decisions_supersedes_id_findings FOREIGN KEY(case_id, supersedes_id) REFERENCES findings (case_id, id), \n\tCONSTRAINT fk_decisions_source_message_id_messages FOREIGN KEY(case_id, source_message_id) REFERENCES messages (case_id, id), \n\tCONSTRAINT fk_decisions_decision_id_decisions FOREIGN KEY(case_id, decision_id) REFERENCES decisions (case_id, id), \n\tCONSTRAINT fk_findings_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_findings_created_by_users FOREIGN KEY(created_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE alerts (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\tkind TEXT NOT NULL, \n\ttitle TEXT NOT NULL, \n\tsummary TEXT NOT NULL, \n\tevidence_ids UUID[] NOT NULL, \n\titem_id UUID, \n\tdiversity JSONB NOT NULL, \n\tconfig_version TEXT NOT NULL, \n\tstatus TEXT DEFAULT 'OPEN' NOT NULL, \n\tfinding_id UUID, \n\tassigned_to UUID, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\thandled_at TIMESTAMP WITH TIME ZONE, \n\thandled_by UUID, \n\tdecision_id UUID, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_alerts PRIMARY KEY (id), \n\tCONSTRAINT uq_alerts_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT ck_alerts_kind CHECK (kind IN ('NEW_HIT', 'TREND', 'WALLET_ACTIVITY', 'KEY_CHANGE', 'ONION_STATUS', 'IMAGE_MATCH', 'MONITOR_ERROR', 'OVERFLOW')), \n\tCONSTRAINT fk_monitor_item_id_watchlist_items FOREIGN KEY(case_id, item_id) REFERENCES watchlist_items (case_id, id), \n\tCONSTRAINT ck_alerts_status CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'DISMISSED', 'ESCALATED')), \n\tCONSTRAINT fk_monitor_finding_id_findings FOREIGN KEY(case_id, finding_id) REFERENCES findings (case_id, id), \n\tCONSTRAINT fk_monitor_decision_id_decisions FOREIGN KEY(case_id, decision_id) REFERENCES decisions (case_id, id), \n\tCONSTRAINT fk_alerts_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id), \n\tCONSTRAINT fk_alerts_assigned_to_users FOREIGN KEY(assigned_to) REFERENCES users (id), \n\tCONSTRAINT fk_alerts_handled_by_users FOREIGN KEY(handled_by) REFERENCES users (id)\n)"
    )
    op.execute(
        "CREATE TABLE monitor_hits (\n\tid UUID DEFAULT gen_random_uuid() NOT NULL, \n\tcase_id UUID NOT NULL, \n\trun_id UUID NOT NULL, \n\titem_id UUID NOT NULL, \n\tevidence_id UUID, \n\turl_hash TEXT NOT NULL, \n\tcontent_hash TEXT NOT NULL, \n\trelevance FLOAT NOT NULL, \n\talertable BOOLEAN NOT NULL, \n\treasons JSONB NOT NULL, \n\talert_id UUID, \n\tat TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tCONSTRAINT pk_monitor_hits PRIMARY KEY (id), \n\tCONSTRAINT uq_monitor_hits_case_id_id UNIQUE (case_id, id), \n\tCONSTRAINT uq_monitor_hits_item_id_content_hash UNIQUE (item_id, content_hash), \n\tCONSTRAINT fk_monitor_run_id_monitor_runs FOREIGN KEY(case_id, run_id) REFERENCES monitor_runs (case_id, id), \n\tCONSTRAINT fk_monitor_item_id_watchlist_items FOREIGN KEY(case_id, item_id) REFERENCES watchlist_items (case_id, id), \n\tCONSTRAINT fk_monitor_evidence_id_evidence FOREIGN KEY(case_id, evidence_id) REFERENCES evidence (case_id, id), \n\tCONSTRAINT fk_monitor_alert_id_alerts FOREIGN KEY(case_id, alert_id) REFERENCES alerts (case_id, id), \n\tCONSTRAINT fk_monitor_hits_case_id_cases FOREIGN KEY(case_id) REFERENCES cases (id)\n)"
    )
    op.execute("CREATE INDEX ix_threads_case_id ON threads (case_id)")
    op.execute("CREATE INDEX ix_runs_case_id ON runs (case_id)")
    op.execute(
        "CREATE UNIQUE INDEX uq_runs_active_thread ON runs (thread_id) WHERE status IN ('QUEUED', 'RUNNING')"
    )
    op.execute("CREATE INDEX ix_messages_case_id ON messages (case_id)")
    op.execute("CREATE INDEX ix_tool_calls_case_id ON tool_calls (case_id)")
    op.execute("CREATE INDEX ix_run_events_case_id ON run_events (case_id)")
    op.execute("CREATE INDEX ix_replay_entries_case_id ON replay_entries (case_id)")
    op.execute("CREATE INDEX ix_rate_counters_case_id ON rate_counters (case_id)")
    op.execute("CREATE INDEX ix_analytic_runs_case_id ON analytic_runs (case_id)")
    op.execute("CREATE INDEX ix_link_candidates_case_id ON link_candidates (case_id)")
    op.execute("CREATE INDEX ix_activity_candidates_case_id ON activity_candidates (case_id)")
    op.execute("CREATE INDEX ix_wallet_assessments_case_id ON wallet_assessments (case_id)")
    op.execute("CREATE INDEX ix_trend_buckets_case_id ON trend_buckets (case_id)")
    op.execute("CREATE INDEX ix_graph_edges_case_id ON graph_edges (case_id)")
    op.execute("CREATE INDEX ix_ledger_nodes_case_id ON ledger_nodes (case_id)")
    op.execute("CREATE INDEX ix_ledger_edges_case_id ON ledger_edges (case_id)")
    op.execute("CREATE INDEX ix_ledger_addresses_case_id ON ledger_addresses (case_id)")
    op.execute("CREATE INDEX ix_audit_events_case_id ON audit_events (case_id)")
    op.execute("CREATE UNIQUE INDEX uq_users_username_lower ON users (lower(username))")
    op.execute("CREATE INDEX ix_api_tokens_case_id ON api_tokens (case_id)")
    op.execute("CREATE INDEX ix_case_memberships_case_id ON case_memberships (case_id)")
    op.execute("CREATE INDEX ix_decisions_case_id ON decisions (case_id)")
    op.execute(
        "CREATE UNIQUE INDEX uq_decisions_initial_target ON decisions (case_id, target_type, target_id, target_version) WHERE supersedes_id IS NULL"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_decisions_supersedes ON decisions (supersedes_id) WHERE supersedes_id IS NOT NULL"
    )
    op.execute("CREATE INDEX ix_findings_case_id ON findings (case_id)")
    op.execute("CREATE INDEX ix_evidence_case_id ON evidence (case_id)")
    op.execute("CREATE INDEX ix_custody_events_case_id ON custody_events (case_id)")
    op.execute("CREATE INDEX ix_derivatives_case_id ON derivatives (case_id)")
    op.execute("CREATE INDEX ix_evidence_code_counters_case_id ON evidence_code_counters (case_id)")
    op.execute("CREATE INDEX ix_extraction_runs_case_id ON extraction_runs (case_id)")
    op.execute(
        "CREATE UNIQUE INDEX uq_extraction_bundle ON extraction_runs (evidence_id, bundle_version) WHERE evidence_id IS NOT NULL"
    )
    op.execute("CREATE INDEX ix_canonical_entities_case_id ON canonical_entities (case_id)")
    op.execute("CREATE INDEX ix_observations_case_id ON observations (case_id)")
    op.execute("CREATE INDEX ix_watchlists_case_id ON watchlists (case_id)")
    op.execute("CREATE INDEX ix_watchlist_items_case_id ON watchlist_items (case_id)")
    op.execute("CREATE INDEX ix_monitor_runs_case_id ON monitor_runs (case_id)")
    op.execute("CREATE INDEX ix_monitor_hits_case_id ON monitor_hits (case_id)")
    op.execute("CREATE INDEX ix_monitor_seen_urls_case_id ON monitor_seen_urls (case_id)")
    op.execute("CREATE INDEX ix_alerts_case_id ON alerts (case_id)")
    op.execute("CREATE INDEX ix_policy_decisions_case_id ON policy_decisions (case_id)")
    op.execute("CREATE INDEX ix_chunks_case_id ON chunks (case_id)")
    op.execute(
        "CREATE INDEX ix_chunks_embedding ON chunks USING hnsw (embedding vector_cosine_ops) WITH (m = 16, ef_construction = 64)"
    )
    op.execute("CREATE INDEX ix_chunks_text_trgm ON chunks USING gin (text gin_trgm_ops)")
    op.execute("CREATE INDEX ix_chunks_tsv ON chunks USING gin (tsv)")
    op.execute("CREATE INDEX ix_reports_case_id ON reports (case_id)")
    op.execute(
        "CREATE FUNCTION darknetra_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '% is append-only', TG_TABLE_NAME; END $$"
    )
    op.execute(
        "CREATE FUNCTION darknetra_no_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '% cannot be deleted', TG_TABLE_NAME; END $$"
    )
    op.execute(
        "CREATE FUNCTION darknetra_evidence_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF (to_jsonb(NEW) - 'status' - 'warnings') IS DISTINCT FROM (to_jsonb(OLD) - 'status' - 'warnings') THEN RAISE EXCEPTION 'evidence content and provenance are immutable'; END IF; RETURN NEW; END $$"
    )
    op.execute(
        "CREATE TRIGGER audit_events_append_only BEFORE UPDATE OR DELETE ON audit_events FOR EACH ROW EXECUTE FUNCTION darknetra_append_only()"
    )
    op.execute(
        "CREATE TRIGGER decisions_append_only BEFORE UPDATE OR DELETE ON decisions FOR EACH ROW EXECUTE FUNCTION darknetra_append_only()"
    )
    op.execute(
        "CREATE TRIGGER evidence_no_delete BEFORE DELETE ON evidence FOR EACH ROW EXECUTE FUNCTION darknetra_no_delete()"
    )
    op.execute(
        "CREATE TRIGGER custody_events_no_delete BEFORE DELETE ON custody_events FOR EACH ROW EXECUTE FUNCTION darknetra_no_delete()"
    )
    op.execute(
        "CREATE TRIGGER derivatives_no_delete BEFORE DELETE ON derivatives FOR EACH ROW EXECUTE FUNCTION darknetra_no_delete()"
    )
    op.execute(
        "CREATE TRIGGER reports_no_delete BEFORE DELETE ON reports FOR EACH ROW EXECUTE FUNCTION darknetra_no_delete()"
    )
    op.execute(
        "CREATE TRIGGER evidence_immutable BEFORE UPDATE ON evidence FOR EACH ROW EXECUTE FUNCTION darknetra_evidence_immutable()"
    )


def downgrade() -> None:
    raise RuntimeError(
        "Evidence-preserving baseline cannot be downgraded; restore an approved backup"
    )
