from enum import StrEnum


class Permission(StrEnum):
    CASE_CREATE = "CASE_CREATE"
    CASE_READ = "CASE_READ"
    CASE_UPDATE = "CASE_UPDATE"
    CASE_CLOSE = "CASE_CLOSE"
    CASE_REOPEN = "CASE_REOPEN"
    CASE_MEMBERSHIP_MANAGE = "CASE_MEMBERSHIP_MANAGE"
    USER_READ = "USER_READ"
    USER_MANAGE = "USER_MANAGE"
    ROLE_READ = "ROLE_READ"
    AUDIT_READ = "AUDIT_READ"
    SYSTEM_HEALTH_READ = "SYSTEM_HEALTH_READ"
