import type { CaseSummary } from './types';

const commonMetadata = {
  collectionStatus: 'Authority recorded',
  createdAt: '2026-08-10T09:00:00Z',
  processStage: 'Collection',
  sourceAuthority: 'Authorized case material retained for workspace validation',
} satisfies Pick<CaseSummary, 'collectionStatus' | 'createdAt' | 'processStage' | 'sourceAuthority'>;

export const FIXTURE_CASES: CaseSummary[] = [
  {
    ...commonMetadata,
    caseCode: 'SYN-DEMO-001',
    id: 'SYN-DEMO-001',
    title: 'Alias correlation training case',
    status: 'OPEN',
    sensitivity: 'STANDARD',
    sourceClass: 'SYNTHETIC',
    owner: 'Demo Administrator',
    evidenceCount: 37,
    pendingReviews: 4,
    openAlerts: 2,
    updatedAt: '2026-08-17T15:45:00Z',
  },
  {
    ...commonMetadata,
    caseCode: 'RES-ARCH-002',
    id: 'RES-ARCH-002',
    title: 'Research archive terminology review',
    status: 'REVIEW',
    sensitivity: 'RESTRICTED',
    sourceClass: 'RESEARCH_ARCHIVE',
    owner: 'Demo Analyst',
    evidenceCount: 19,
    pendingReviews: 2,
    openAlerts: 1,
    processStage: 'Review',
    updatedAt: '2026-08-16T10:20:00Z',
  },
  {
    ...commonMetadata,
    caseCode: 'SYN-DEMO-003',
    id: 'SYN-DEMO-003',
    title: 'Parcel-language pattern simulation',
    status: 'OPEN',
    sensitivity: 'STANDARD',
    sourceClass: 'SYNTHETIC',
    owner: 'Demo Analyst',
    evidenceCount: 24,
    pendingReviews: 1,
    openAlerts: 0,
    updatedAt: '2026-08-15T12:05:00Z',
  },
  {
    ...commonMetadata,
    caseCode: 'SYN-DEMO-004',
    id: 'SYN-DEMO-004',
    title: 'Image reuse hard-negative exercise',
    status: 'OPEN',
    sensitivity: 'RESTRICTED',
    sourceClass: 'SYNTHETIC',
    owner: 'Demo Reviewer',
    evidenceCount: 16,
    pendingReviews: 3,
    openAlerts: 1,
    updatedAt: '2026-08-14T08:35:00Z',
  },
  {
    ...commonMetadata,
    caseCode: 'SYN-DEMO-005',
    id: 'SYN-DEMO-005',
    title: 'Closed baseline corpus validation',
    status: 'CLOSED',
    sensitivity: 'STANDARD',
    sourceClass: 'SYNTHETIC',
    owner: 'Demo Administrator',
    evidenceCount: 42,
    pendingReviews: 0,
    openAlerts: 0,
    processStage: 'Closed',
    updatedAt: '2026-08-12T17:00:00Z',
  },
  {
    ...commonMetadata,
    caseCode: 'RES-ARCH-006',
    id: 'RES-ARCH-006',
    title: 'Archived marketplace structure study',
    status: 'REVIEW',
    sensitivity: 'RESTRICTED',
    sourceClass: 'RESEARCH_ARCHIVE',
    owner: 'Demo Reviewer',
    evidenceCount: 28,
    pendingReviews: 2,
    openAlerts: 0,
    processStage: 'Review',
    updatedAt: '2026-08-11T11:40:00Z',
  },
];

export function getFixtureCase(caseId: string): CaseSummary | undefined {
  return FIXTURE_CASES.find((item) => item.id === caseId);
}
