import type { CaseSummary } from "./types";

export const OPERATIONAL_SNAPSHOT_CASES: CaseSummary[] = [
  {
    caseCode: "DN-INT-7842",
    collectionStatus: "Authority recorded",
    createdAt: "2026-08-25T07:45:00.000Z",
    evidenceCount: 9,
    id: "snapshot-marketplace-correlation",
    openAlerts: 2,
    owner: "Investigation Lead",
    pendingReviews: 3,
    processStage: "Collection",
    sensitivity: "RESTRICTED",
    sourceAuthority: "Authorized intelligence package",
    sourceClass: "AUTHORIZED_SOURCE",
    status: "OPEN",
    title: "Marketplace alias and wallet correlation",
    updatedAt: "2026-08-25T15:20:00.000Z",
  },
  {
    caseCode: "DN-INT-7829",
    collectionStatus: "Authority recorded",
    createdAt: "2026-08-24T11:10:00.000Z",
    evidenceCount: 7,
    id: "snapshot-image-fingerprint",
    openAlerts: 1,
    owner: "Evidence Analyst",
    pendingReviews: 2,
    processStage: "Review",
    sensitivity: "STANDARD",
    sourceAuthority: "Authorized intelligence package",
    sourceClass: "AUTHORIZED_SOURCE",
    status: "REVIEW",
    title: "Image fingerprint reuse cluster",
    updatedAt: "2026-08-25T14:05:00.000Z",
  },
  {
    caseCode: "DN-INT-7815",
    collectionStatus: "Authority recorded",
    createdAt: "2026-08-23T09:25:00.000Z",
    evidenceCount: 5,
    id: "snapshot-regional-language",
    openAlerts: 0,
    owner: "Regional Review",
    pendingReviews: 2,
    processStage: "Collection",
    sensitivity: "STANDARD",
    sourceAuthority: "Authorized intelligence package",
    sourceClass: "AUTHORIZED_SOURCE",
    status: "OPEN",
    title: "Regional phrase and delivery-pattern review",
    updatedAt: "2026-08-25T12:40:00.000Z",
  },
  {
    caseCode: "DN-INT-7798",
    collectionStatus: "Authority recorded",
    createdAt: "2026-08-22T08:00:00.000Z",
    evidenceCount: 4,
    id: "snapshot-report-package",
    openAlerts: 0,
    owner: "Case Reviewer",
    pendingReviews: 0,
    processStage: "Review",
    sensitivity: "RESTRICTED",
    sourceAuthority: "Authorized intelligence package",
    sourceClass: "AUTHORIZED_SOURCE",
    status: "REVIEW",
    title: "Report package readiness review",
    updatedAt: "2026-08-25T10:15:00.000Z",
  },
];

export const OPERATIONAL_SNAPSHOT_METRICS = {
  failedJobs: 0,
  integrityWarnings: 2,
  openAlerts: OPERATIONAL_SNAPSHOT_CASES.reduce((total, item) => total + item.openAlerts, 0),
  pendingReviews: OPERATIONAL_SNAPSHOT_CASES.reduce((total, item) => total + item.pendingReviews, 0),
};
